plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/private/tmp/claude-501/-Users-jeonjei/f20b2407-902b-4c85-b4d5-e76fc8bf7d26/scratchpad/StudyNotes"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]