plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/private/tmp/claude-501/-Users-jeonjei/0e361ee4-d203-4a86-be6e-385bbce5f897/scratchpad/StudyNotes"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]